- name: minio-client
  matrix:
    architectures:
      - amd64
      - arm64
      - armhf
    versions:
      - 2022-04-16T21-11-21Z
      - 2022-06-11T21-10-36Z
      - 2022-07-29T19-17-16Z
      - 2022-08-05T08-01-28Z
      - 2022-12-24T15-21-38Z
      - 2023-03-20T17-17-53Z
      - 2023-05-30T22-41-38Z
      - 2023-08-15T23-03-09Z
      - 2024-10-29T15-34-59Z
  homepage: https://min.io
  summary: command-line interface for MinIO (mc)
  description: |-
    MinIO Client (mc) is a replacement for ls, cp, mkdir, diff and rsync commands
    for filesystems and object storage.
  fetch: https://dl.min.io/client/mc/release/linux-{{goarch}}/archive/mc.RELEASE.{{version}}
  install:
    - mc.RELEASE.{{version}}:/usr/bin/mc

- name: minio-client
  matrix:
    architectures:
      - amd64
      - arm64
    versions:
      - 2024-11-05T11-29-45Z
  homepage: https://min.io
  summary: command-line interface for MinIO (mc)
  description: |-
    MinIO Client (mc) is a replacement for ls, cp, mkdir, diff and rsync commands
    for filesystems and object storage.
  fetch: https://dl.min.io/client/mc/release/linux-{{goarch}}/archive/mc.RELEASE.{{version}}
  install:
    - mc.RELEASE.{{version}}:/usr/bin/mc
